// The four narrowphase and sleep rules issue #392 turned over, each pinned by
// the case that broke before it.
//
// Every one of them was found by the real-data probe against a vanilla
// farmhouse and none of them was visible from the suites that existed at the
// time, because all four need geometry that the synthetic fixtures did not
// have: a body whose collider does not straddle its own centre of mass, a solid
// slab with a far face, a sample generating the same contact through several
// placed shapes, and two bodies settling side by side. The fixtures here are
// still synthetic — boxes and quads described in code — but they are shaped
// like the real cases now.

@testable import opensky
import simd
import Testing

struct DynamicNarrowphaseTests {
    /// A floor quad at z = 0 wound so its front face points up, and a body whose
    /// collider sits entirely *above* its centre of mass, which is what vanilla
    /// clutter does and what the old orient-toward-the-centre rule could not
    /// survive.
    @Test
    func aSurfaceFacesTheWayItIsWoundNotTheWayTheBodyLies() throws {
        let floor = DynamicBodyScene.floor()
        let above = try #require(DynamicBodyContacts.penetration(
            of: SIMD3(0, 0, 1), radius: 4, shape: floor
        ))
        #expect(above.normal.z > 0.99, "a sample over a floor is pushed up")

        // The same sample, a hair *under* the floor. Under the old rule this
        // depended on where the body's centre of mass happened to be; the
        // winding gives the same answer either way, which is what stops a body
        // that has dipped below a surface being expelled through it.
        let below = try #require(DynamicBodyContacts.penetration(
            of: SIMD3(0, 0, -1), radius: 4, shape: floor
        ))
        #expect(below.normal.z > 0.99, "a sample under a floor is still pushed up")
        #expect(below.depth > above.depth, "the deeper sample has the deeper contact")
    }

    /// A box's triangle connectivity is generated by this engine, not authored,
    /// so its facing comes from the shape's own interior instead.
    @Test
    func aBoxFacesAwayFromItsOwnCentre() throws {
        let box = StaticCollisionShape(
            reference: FormID(3),
            transform: MatrixMath.translation(SIMD3(0, 0, 100)),
            geometry: .box(halfExtents: SIMD3(50, 50, 10)),
            bounds: ModelBounds(min: SIMD3(-50, -50, 90), max: SIMD3(50, 50, 110))
        )
        let overTheTop = try #require(DynamicBodyContacts.penetration(
            of: SIMD3(0, 0, 111), radius: 4, shape: box
        ))
        #expect(overTheTop.normal.z > 0.99)
        let underTheBottom = try #require(DynamicBodyContacts.penetration(
            of: SIMD3(0, 0, 89), radius: 4, shape: box
        ))
        #expect(underTheBottom.normal.z < -0.99)
    }

    /// The nearest surface of a shape decides, and a near face saying "outside"
    /// vetoes a far one saying "deep inside".
    ///
    /// Without the veto, a body hovering a few units over a shelf board found
    /// the board's underside twenty units away, was told it was twenty units
    /// inside the board, and was driven down through the shelf — measured on
    /// real data, and reproduced here on a slab.
    @Test
    func aSampleClearOfASlabGetsNoContactFromItsFarFace() {
        let slab = StaticCollisionShape(
            reference: FormID(4),
            transform: MatrixMath.translation(SIMD3(0, 0, 100)),
            geometry: .box(halfExtents: SIMD3(200, 200, 8)),
            bounds: ModelBounds(min: SIMD3(-200, -200, 92), max: SIMD3(200, 200, 108))
        )
        // Seventeen units above the top face, and thirty-three above the
        // underside. Both are inside `recoveryDepth` of the slab.
        let hit = DynamicBodyContacts.penetration(
            of: SIMD3(0, 0, 125), radius: 4, shape: slab
        )
        #expect(hit == nil, "a sample well clear of a slab is not inside it")
    }

    /// One sample reaching one surface through several placed shapes still moves
    /// the body by one penetration's worth, not by one per shape.
    ///
    /// This is the shape of the real failure: vanilla places overlapping
    /// collision shapes, a hull corner resting in a shelf generates the same
    /// contact through each of them, and applying every one of them in turn once
    /// shot a crate 118 units through a farmhouse floor in a single step.
    @Test
    func redundantContactsCorrectOnceRatherThanOncePerContact() {
        let copies = (0 ..< 6).map { _ in DynamicBodyScene.floor(z: 100) }
        let world = DynamicStepWorld(staticCandidates: DynamicBodyScene.query(copies))
        var bodies = [DynamicBodyScene.cube(key: .generated(1), center: SIMD3(0, 0, 104))]
        let start = bodies[0].position.z

        DynamicBodyScene.run(bodies: &bodies, world: world, steps: 1)

        // Six coincident floors describe one six-unit penetration. Correcting
        // per contact would move the body six times that in one step.
        #expect(bodies[0].position.z - start <= DynamicBodySolver.maximumCorrectionDistance + 1e-3)
    }

    /// The angular sleep threshold is the spin at which the collider's outermost
    /// point moves at the linear threshold, so it means the same motion on a cup
    /// as on a table.
    @Test
    func theAngularSleepThresholdFollowsTheColliderSize() {
        let small = DynamicBodyScene.cube(key: .generated(1), center: .zero, half: 4)
        let large = DynamicBodyScene.cube(key: .generated(2), center: .zero, half: 120)
        #expect(
            DynamicBodySolver.sleepAngularSpeed(of: small)
                > DynamicBodySolver.sleepAngularSpeed(of: large)
        )
        #expect(
            DynamicBodySolver.sleepAngularSpeed(of: small)
                <= DynamicBodySolver.maximumSleepAngularSpeed
        )
    }

    /// Two bodies settled against each other both sleep.
    ///
    /// They did not before: a body stays awake for `sleepStepCount` steps after
    /// it stops moving, and waking a neighbour on mere wakefulness made the pair
    /// alternate forever — one sleeping on step 61 and woken on step 62, over
    /// and over. Neither can be persisted while that lasts, because a resting
    /// transform is only recorded the step a body falls asleep.
    @Test
    func neighboursSettledAgainstEachOtherBothSleep() {
        let world = DynamicStepWorld(
            staticCandidates: DynamicBodyScene.query([DynamicBodyScene.floor()])
        )
        var bodies = [
            DynamicBodyScene.cube(key: .generated(1), center: SIMD3(-9, 0, 40)),
            DynamicBodyScene.cube(key: .generated(2), center: SIMD3(9, 0, 60))
        ]

        DynamicBodyScene.run(bodies: &bodies, world: world, steps: 600)

        #expect(bodies[0].isSleeping, "a touching pair kept waking each other")
        #expect(bodies[1].isSleeping, "a touching pair kept waking each other")
    }
}
